version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    command: /bin/sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
